#   /$$$$$$                      /$$           /$$$$$$$                                                   
#  /$$__  $$                    |__/          | $$__  $$                                                  
# | $$  \__/  /$$$$$$   /$$$$$$$ /$$  /$$$$$$ | $$  \ $$  /$$$$$$  /$$   /$$ /$$$$$$$   /$$$$$$$  /$$$$$$ 
# | $$       |____  $$ /$$_____/| $$ /$$__  $$| $$$$$$$  /$$__  $$| $$  | $$| $$__  $$ /$$_____/ /$$__  $$
# | $$        /$$$$$$$|  $$$$$$ | $$| $$$$$$$$| $$__  $$| $$  \ $$| $$  | $$| $$  \ $$| $$      | $$$$$$$$
# | $$    $$ /$$__  $$ \____  $$| $$| $$_____/| $$  \ $$| $$  | $$| $$  | $$| $$  | $$| $$      | $$_____/
# |  $$$$$$/|  $$$$$$$ /$$$$$$$/| $$|  $$$$$$$| $$$$$$$/|  $$$$$$/|  $$$$$$/| $$  | $$|  $$$$$$$|  $$$$$$$
#  \______/  \_______/|_______/ |__/ \_______/|_______/  \______/  \______/ |__/  |__/ \_______/ \_______/
# 
# --------------------------------------------------------------------------------------------------------
# If the WorldGuard Flags are enabled or not. Once enabled you have to fully restart your server so the flags
# can be registered in WorldGuard. NOTE: the flag registration can not be undone! You will always see the flags
# in the flag list, even when CasieBounce is not enabled. (1.13+ Only)
WorldGuardFlags: false
# --------------------------------------------------------------------------------------------------------

# ------------------------------------------- DEFAULT SETTINGS -------------------------------------------
# How high you will bounce, just experiment with it :)
BounceForce: 0.7

# The sound that will be played when you bounce. (Set to NONE to disable)
BounceSound: BLOCK_SLIME_HIT

# Whether you will stop bouncing when you crouch.
StopWhenCrouch: true

# Whether you take FallDamage. Use: 'ENABLED', 'DISABLED' or 'REDUCED'
FallDamage: DISABLED
# The death message. (Color codes supported)
DeathMessage: '%player% fell while bouncing'

# Whether you need the permission CB.bounce.
RequirePermission: false

# The blocks where you can bounce on.  (Legacy use: WOOL:1 || 1.13+ use: ORANGE_WOOL)
BounceBlocks:
   - WOOL:1
   - CONCRETE:11

   - ORANGE_WOOL
   - BLUE_CONCRETE
# If the blocklist above is a blacklist. When true you can bounce on every block except the ones above.
IsBlockBlacklist: false
# --------------------------------------------------------------------------------------------------------
# By: CasieBarie || Source Code: https://github.com/CasieBarieDev/CasieBounce || Support: https://discord.gg/ZptCBHeHyg