#  _____           _     ______                            
# /  __ \         (_)    | ___ \                           
# | /  \/ __ _ ___ _  ___| |_/ / ___  _   _ _ __   ___ ___ 
# | |    / _` / __| |/ _ \ ___ \/ _ \| | | | '_ \ / __/ _ \
# | \__/\ (_| \__ \ |  __/ |_/ / (_) | |_| | | | | (_|  __/
#  \____/\__,_|___/_|\___\____/ \___/ \__,_|_| |_|\___\___|
#  
# -----------------------------------------------------------------------------------------
# How high you will bounce, just experiment with it :)
Bounceforce: 0.7

#The sound that will be played when you bounce.
BounceSound: BLOCK_SLIME_HIT

# Whether you will stop bouncing when you crouch.
StopWhenCrouch: true

# Whether you take FallDamage.
FallDamage: false
# The death message. (Color codes supported)
DeathMessage: '%player% fell while bouncing'

# Whether you need the permission CB.bounce.
RequirePermission: false

# The names of the WorldGuard regions. (Only works when WorldGuard is installed {Use GLOBAL to make it work everywhere, make sure when you use GLOBAL to not specify other regions})
Regions:
   - regionname
# If the regionlist above is a blacklist. When true you can bounce in every region exept the ones above. (GLOBAL will disable the bouncing)
IsRegionBlacklist: false

# The blocks where you can bounce on.  (Legacy use: WOOL:1 || 1.13+ use: ORANGE_WOOL)
BounceBlocks:
   - WOOL:1
   - CONCRETE:11

   - ORANGE_WOOL
   - BLUE_CONCRETE
# If the blocklist above is a blacklist. When true you can bounce on every block exept the ones above.
IsBlockBlacklist: false

# -----------------------------------------------------------------------------------------
# By: CasieBarie || Source Code: https://github.com/CasieBarieDev/CasieBounce || Support: https://discord.gg/ZptCBHeHyg